version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  lint:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run:
          name: Lint php code
          command: |
            php -l ./app/index.php
workflows:
  default:
    jobs:
      - lint
      - docker/publish:
          image: abdelazim/capstone
