version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run:
          name: Lint php code
          command: |
            php -l ./app/index.php
  dockerize:
    docker:
      - image: docker
    steps:
      - checkout  
      - run:
          name: Dockerize the app
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker --version
            docker build -t ml-microservice .
            docker tag ml-microservice abdelazim/capstone
            docker push abdelazim/capstone
workflows:
  default:
    jobs:
      - lint
      - dockerize
