version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run:
          name: Lint php code
          command: |
            php -l ./app/index.php
  dockerize:
    docker:
      - image: circleci/docker-gc
    steps:
      - checkout  
      - run:
          name: Dockerize the app
          command: |
            docker --version
workflows:
  default:
    jobs:
      - lint
