apiVersion: v1
kind: Service
metadata:
  name: capstone-service-{{WorkflowID}}
spec:
  type: LoadBalancer
  selector:
    app: capstone-{{WorkflowID}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80